import * as THREE from 'three';
import type { PaintingMapRole } from './PaintingTextureSet';

/**
 * Deterministic procedural texture generator for the v0.02 painting material.
 *
 * Generates believable canvas/brush relief, roughness, and specular maps so
 * the gallery looks correct without any authored scanned assets. The factory
 * owns every texture it creates and is solely responsible for disposing them.
 *
 * Aspect-ratio note: the factory itself produces square tiles. Aspect-aware
 * tiling is applied by the consumer (via `repeat` and `uDetailTiling`) using
 * the artwork's world-space width/height, so a portrait, landscape, square,
 * or ultrawide painting all show square canvas weave at the same physical
 * thread density.
 */
export class ProceduralTextureFactory {
  private readonly cache = new Map<string, THREE.Texture>();
  /**
   * v0.06: cap applied to every DataTexture generated by this factory.
   * Mirrors `TextureManager.getEffectiveAnisotropy()` and is updated by
   * `GalleryManager.applyPreset()` on every quality-preset switch. Defaults
   * to 1 so behaviour matches v0.05 until a preset is applied.
   */
  private currentAnisotropy = 1;

  /**
   * Returns (and caches) the procedural texture for an artwork+role.
   * v0.03: `tileSize` is part of the cache key so a preset change re-generates
   * the maps at the new resolution instead of returning a stale tile.
   */
  generate(artworkId: string, role: PaintingMapRole, tileSize?: number): THREE.Texture {
    const effectiveSize = Math.max(64, tileSize ?? 256);
    const cacheKey = `${artworkId}::${role}::${effectiveSize}`;
    const cached = this.cache.get(cacheKey);
    if (cached) return cached;

    const seed = this.hash(artworkId);
    // Roughness/specular need less resolution than the geometry-carrying maps.
    const smallSize = Math.max(64, Math.floor(effectiveSize / 2));

    let tex: THREE.Texture;
    switch (role) {
      case 'normal':
        tex = this.generateNormal(seed, effectiveSize, 14, 6, 3, 0.42);
        break;
      case 'detailNormal':
        tex = this.generateNormal(seed * 7 + 13, effectiveSize, 18, 7, 2.5, 1.1);
        tex.wrapS = THREE.RepeatWrapping;
        tex.wrapT = THREE.RepeatWrapping;
        break;
      case 'height':
        tex = this.generateHeight(seed, effectiveSize);
        break;
      case 'roughness':
        tex = this.generateRoughness(seed, smallSize);
        break;
      case 'specular':
        tex = this.generateSpecular(seed, smallSize);
        break;
      case 'ao':
        tex = this.generateAO(seed, effectiveSize);
        break;
      case 'varnish':
        tex = this.generateVarnish(seed, smallSize);
        break;
      case 'albedo':
      default:
        tex = this.generateAlbedo(seed);
        break;
    }

    this.cache.set(cacheKey, tex);
    tex.anisotropy = this.currentAnisotropy;
    return tex;
  }

  /** Disposes every generated texture. Call only on application shutdown. */
  disposeAll(): void {
    this.cache.forEach((tex) => tex.dispose());
    this.cache.clear();
  }

  /**
   * v0.06: applies `value` to every generated texture already in the cache,
   * and stores it so future `generate()` calls apply it to new textures
   * immediately. Call from `GalleryManager.applyPreset()` with
   * `TextureManager.getEffectiveAnisotropy()` so authored and procedural
   * textures share the same per-preset anisotropy cap.
   *
   * No-op when the value has not changed. Mutates cached textures in place
   * (no new GPU uploads — `anisotropy` is a sampler-state property).
   */
  setAnisotropy(value: number): void {
    const a = Math.max(1, value | 0);
    if (a === this.currentAnisotropy) return;
    this.currentAnisotropy = a;
    this.cache.forEach((tex) => {
      tex.anisotropy = a;
      tex.needsUpdate = true;
    });
  }

  // ── Map generators ────────────────────────────────────────────────────────

  /**
   * Tangent-space normal map. Pseudocode follows §Procedural Map Generation
   * in plan.md. RGB encodes (Nx, Ny, Nz) packed to [0..1].
   * Frequencies chosen so the texture has clean canvas-weave appearance.
   */
  private generateNormal(
    seed: number,
    size: number,
    oct1Amp: number,
    oct2Amp: number,
    _weaveAmp: number,
    freqScale: number
  ): THREE.Texture {
    const data = new Uint8Array(size * size * 4);
    const f1 = 0.055 * freqScale;
    const f2 = 0.14 * freqScale;

    for (let y = 0; y < size; y += 1) {
      for (let x = 0; x < size; x += 1) {
        const idx = (y * size + x) * 4;

        const h1 = this.valueNoise2d(x * f1, y * f1, seed);
        const h1x = this.valueNoise2d((x + 1) * f1, y * f1, seed);
        const h1y = this.valueNoise2d(x * f1, (y + 1) * f1, seed);
        const h2 = this.valueNoise2d(x * f2, y * f2, seed + 17);
        const h2x = this.valueNoise2d((x + 1) * f2, y * f2, seed + 17);
        const h2y = this.valueNoise2d(x * f2, (y + 1) * f2, seed + 17);

        const gx = (h1x - h1) * oct1Amp + (h2x - h2) * oct2Amp;
        const gy = (h1y - h1) * oct1Amp + (h2y - h2) * oct2Amp;

        data[idx + 0] = this.clamp8(128 + gx * 28);
        data[idx + 1] = this.clamp8(128 + gy * 28);
        data[idx + 2] = 255;
        data[idx + 3] = 255;
      }
    }

    return this.makeDataTexture(data, size, size, /* sRGB */ false);
  }

  /** Grayscale R-channel height. Horizontal brush strokes + cross-hatch + tooth grain. */
  private generateHeight(seed: number, size: number): THREE.Texture {
    const data = new Uint8Array(size * size * 4);

    for (let y = 0; y < size; y += 1) {
      for (let x = 0; x < size; x += 1) {
        const idx = (y * size + x) * 4;
        const macro = this.valueNoise2d(x * 0.04, y * 0.04, seed) * 90;
        const mid = this.valueNoise2d(x * 0.12, y * 0.09, seed + 7) * 40;
        const micro = this.valueNoise2d(x * 0.55, y * 0.55, seed + 31) * 16;
        const h = this.clamp8(macro + mid + micro);
        data[idx + 0] = h;
        data[idx + 1] = h;
        data[idx + 2] = h;
        data[idx + 3] = 255;
      }
    }

    return this.makeDataTexture(data, size, size, false);
  }

  /**
   * Matte-canvas roughness in the [140..240] range (v0.03 retune).
   * Previous v0.02 range [60..220] occasionally landed in semi-gloss territory,
   * which conflicted with the matte-first goal.
   */
  private generateRoughness(seed: number, size: number): THREE.Texture {
    const data = new Uint8Array(size * size * 4);

    for (let y = 0; y < size; y += 1) {
      for (let x = 0; x < size; x += 1) {
        const idx = (y * size + x) * 4;
        const lo = this.valueNoise2d(x * 0.07, y * 0.07, seed + 3);
        const hi = this.valueNoise2d(x * 0.24, y * 0.24, seed + 19);
        const combined = lo * 0.65 + hi * 0.35;
        const r = this.clamp8(140 + combined * 100);
        data[idx + 0] = r;
        data[idx + 1] = r;
        data[idx + 2] = r;
        data[idx + 3] = 255;
      }
    }

    return this.makeDataTexture(data, size, size, false);
  }

  /**
   * Subtle specular variation (v0.03 retune): baseline ~6 with gentle blobs
   * peaking at ~90 instead of dominating Gaussian highlights. Keeps the
   * painting matte by default while still letting varnish patches catch
   * grazing light.
   */
  private generateSpecular(seed: number, size: number): THREE.Texture {
    const data = new Uint8Array(size * size * 4);

    for (let i = 0; i < size * size; i += 1) {
      data[i * 4 + 0] = 6;
      data[i * 4 + 1] = 6;
      data[i * 4 + 2] = 6;
      data[i * 4 + 3] = 255;
    }

    const blobCount = 4 + (seed % 4);
    for (let b = 0; b < blobCount; b += 1) {
      const cx = ((seed * (b + 7)) % size);
      const cy = ((seed * (b + 13) * 3) % size);
      const radius = 14 + ((seed * (b + 1)) % 18);

      for (let y = 0; y < size; y += 1) {
        for (let x = 0; x < size; x += 1) {
          const dx = x - cx;
          const dy = y - cy;
          const distSq = dx * dx + dy * dy;
          const blob = Math.exp(-distSq / (radius * radius)) * 90;
          const idx = (y * size + x) * 4;
          const r = this.clamp8(data[idx] + blob);
          data[idx + 0] = r;
          data[idx + 1] = r;
          data[idx + 2] = r;
        }
      }
    }

    return this.makeDataTexture(data, size, size, false);
  }

  /** Neutral AO fallback. No fake vignette — authored AO may still add real occlusion. */
  private generateAO(seed: number, size: number): THREE.Texture {
    const data = new Uint8Array(size * size * 4);

    for (let y = 0; y < size; y += 1) {
      for (let x = 0; x < size; x += 1) {
        const idx = (y * size + x) * 4;
        const grain = this.valueNoise2d(x * 0.11, y * 0.11, seed) * 18;
        const v = this.clamp8(237 + grain);
        data[idx + 0] = v;
        data[idx + 1] = v;
        data[idx + 2] = v;
        data[idx + 3] = 255;
      }
    }

    return this.makeDataTexture(data, size, size, false);
  }

  /** Subtle deterministic clearcoat fallback mask for future varnished authored profiles. */
  private generateVarnish(seed: number, size: number): THREE.Texture {
    const data = new Uint8Array(size * size * 4);

    for (let y = 0; y < size; y += 1) {
      for (let x = 0; x < size; x += 1) {
        const idx = (y * size + x) * 4;
        const lo = this.valueNoise2d(x * 0.035, y * 0.035, seed + 101);
        const hi = this.valueNoise2d(x * 0.18, y * 0.18, seed + 149);
        const v = this.clamp8((lo * 0.75 + hi * 0.25) * 85);
        data[idx + 0] = v;
        data[idx + 1] = v;
        data[idx + 2] = v;
        data[idx + 3] = 255;
      }
    }

    return this.makeDataTexture(data, size, size, false);
  }

  /** Neutral fallback albedo (very rarely used — `Artwork.image` provides the real picture). */
  private generateAlbedo(seed: number): THREE.Texture {
    const size = 64;
    const data = new Uint8Array(size * size * 4);
    const hue = seed % 32;
    const baseR = 200 + ((hue * 3) % 30);
    const baseG = 200 + ((hue * 5) % 30);
    const baseB = 200 + ((hue * 7) % 30);
    for (let i = 0; i < size * size; i += 1) {
      data[i * 4 + 0] = baseR;
      data[i * 4 + 1] = baseG;
      data[i * 4 + 2] = baseB;
      data[i * 4 + 3] = 255;
    }
    return this.makeDataTexture(data, size, size, /* sRGB */ true);
  }

  // ── Utilities ─────────────────────────────────────────────────────────────

  private makeDataTexture(
    data: Uint8Array,
    width: number,
    height: number,
    srgb: boolean
  ): THREE.DataTexture {
    const tex = new THREE.DataTexture(
      // newer TS lib types tighten Uint8Array<ArrayBufferLike>; cast through
      // an explicit ArrayBuffer-backed view to satisfy the DataTexture sig.
      data as unknown as ArrayBufferView<ArrayBuffer>,
      width,
      height,
      THREE.RGBAFormat,
      THREE.UnsignedByteType
    );
    tex.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.LinearSRGBColorSpace;
    tex.wrapS = THREE.RepeatWrapping;
    tex.wrapT = THREE.RepeatWrapping;
    tex.minFilter = THREE.LinearMipMapLinearFilter;
    tex.magFilter = THREE.LinearFilter;
    tex.generateMipmaps = true;
    tex.needsUpdate = true;
    return tex;
  }

  private clamp8(value: number): number {
    if (value < 0) return 0;
    if (value > 255) return 255;
    return value | 0;
  }

  private hash(value: string): number {
    let result = 0;
    for (let i = 0; i < value.length; i += 1) {
      result = (result * 31 + value.charCodeAt(i)) >>> 0;
    }
    return result || 1;
  }

  private valueNoise2d(x: number, y: number, seed: number): number {
    const xi = Math.floor(x) | 0;
    const yi = Math.floor(y) | 0;
    const xf = x - Math.floor(x);
    const yf = y - Math.floor(y);

    const ux = xf * xf * (3 - 2 * xf);
    const uy = yf * yf * (3 - 2 * yf);

    const h00 = this.latticeHash(xi, yi, seed);
    const h10 = this.latticeHash(xi + 1, yi, seed);
    const h01 = this.latticeHash(xi, yi + 1, seed);
    const h11 = this.latticeHash(xi + 1, yi + 1, seed);

    return (
      h00 * (1 - ux) * (1 - uy) +
      h10 * ux * (1 - uy) +
      h01 * (1 - ux) * uy +
      h11 * ux * uy
    );
  }

  private latticeHash(ix: number, iy: number, seed: number): number {
    let h = (seed * 1664525 + ix * 1013904223) >>> 0;
    h = (h ^ (iy * 1540483477)) >>> 0;
    h = (h ^ (h >>> 16)) >>> 0;
    h = Math.imul(h, 0x45d9f3b) >>> 0;
    h = (h ^ (h >>> 16)) >>> 0;
    return (h >>> 0) / 0xffffffff;
  }
}
